### ISSUE TITLE
Win10 Compiler Failed

### ISSUE THREAD

**Issue by HikariS97** [ultravideo/kvazzup#1]
Hi,
I use qt creator to compile kvazzup but failed.
Here's my folder structure
./msvc_libs
![msvc_libs](https://user-images.githubusercontent.com/48763518/79751297-f46cb080-8344-11ea-8fa9-aadc66e708e3.png)

( Here comes another question. I tried thousand times to compile openHEVC, there's so many compile errors when using cmake and msvc. Finally I got a dll named LibOpenHevcWrapper.dll with out a prefix 'lib'. I use this dll at first, but got a error 'file format not recognized'. Then I replace this dll to the one at openHEVC-hevc_rext\bin\ffmpeg_w32 )

./include
![include](https://user-images.githubusercontent.com/48763518/79751308-f898ce00-8344-11ea-9546-bf14f003bd7c.png)

And I comment off win32-gcc in .pro file. If not, errors like 'cannot find -lkvazaar.dll' appear. But actually, I didn't got dlls for opus, speexdsp and kvazaar.

Finally, I got 1900+ errors like these
![errors1](https://user-images.githubusercontent.com/48763518/79751925-013dd400-8346-11ea-99da-6e8659b1725f.png)
![erros2](https://user-images.githubusercontent.com/48763518/79751930-0438c480-8346-11ea-8de3-80ed2853bfa2.png)

I don't know how to fix these up, could you give me help ?

Here's the screenshot of edited .pro file
![profile](https://user-images.githubusercontent.com/48763518/79752043-39ddad80-8346-11ea-8175-30c3d6b9a40f.png)

**Comment by polusto** [comment]
Hi,

First of all thank you for your interest in Kvazzup. Those libraries can be a bit hard to compile. 

At quick glance it looks like you are using mix of MinGW and MSVC compiled libraries. You should use the same compiler for all libraries and for Kvazzup. Also there is a known issue for compiling kvzRTP with MSVC so I would recommend using MinGW or waiting until the issue is resolved if you want to use MSVC.

**Comment by HikariS97** [comment]
@polusto
Hi, thanks for your advice. I tried to complie those libs by using mingw64 + msys2. Except openHEVC, other static libs are compiled successfullly. But when I try to build kvazzup, some errors appeared. Do you have any idea of these erros? It's more better than the beginning ( 1900+ errors).
![微信图片_20200423154813](https://user-images.githubusercontent.com/48763518/80073148-ddfb6a80-8579-11ea-8cc4-a53aa3b28aba.png)

**Comment by polusto** [comment]
Hard to tell exactly with this information, but it seems that your build environment is missing openMP which is giving you those omp/GOMP errors. As for kvazaar, are you sure you have used the same compiler for it?

**Comment by HikariS97** [comment]
Yes. I use msys2 and mingw64. Compiled by Clang. There's only one error with kvazaar

**Comment by polusto** [comment]
I'm assuming you are mixing 32-bit and 64-bit MinGW builds which to my knowledge does not work. You have to either use 32-bit or 64-bit for all. I'm not familiar with Clang, but I would assume that it works as long as you build the correct binaries.

**Comment by HikariS97** [comment]
@polusto I complied kvazaar by
`./configure --host=x86_64-w64-mingw32`
`make`
I get the static lib named libkvazaar.a (5412kB) 
If I use "Desktop Qt 5.14.2 MinGW 64-bit", I got error  with __imp_kvz_api_get
if I use "Desktop Qt 5.14.2 MinGW 32-bit", the error with kvazaar disappear( but other 64-bit libs alert)
Does it mean I'm building 32-bit lib of kvazaar?

**Comment by HikariS97** [comment]
![微信图片_20200428093551](https://user-images.githubusercontent.com/48763518/80437248-b4549180-8933-11ea-8e4f-32e2f2da8348.png)
It seems like 64-bit

**Comment by fador** [comment]
I think you might have to define KVZ_STATIC_LIB when building Kvazzup, so that the kvazaar.h doesn't define "import library" but the static library functions..

**Comment by polusto** [comment]
I can see the folder msvc_libs in you path which is the default path for MSVC compiler. Are you sure you are using MinGW to compile Kvazzup and have correct libraries at correct places? (which currently is ./lib64 for MinGW libraries).

**Comment by HikariS97** [comment]
Yes, I delete "win32-msvc{" and "win32-g++{".

**Comment by polusto** [comment]
Are you mixing 32 and 64 bit libraries or have you compiled all libraries with either 32 or 64 bit MinGW?

**Comment by HikariS97** [comment]
fador is right. I add #define KVZ_STATIC_LIB in kvazaar.h, then error disappear.

**Comment by polusto** [comment]
That is great. I'll check the compilation process for kvazaar and afterwards I'll close this issue.

**Comment by HikariS97** [comment]
I think it's a confusing process for a rookie to compile kvazzup and dependency libs. If kvzrtp could only be compiled by mingw ( at least, now), u should delete the choice of win32-msvc. And the code in code block win32-g++, which is in .dll format, also confused me. 

LIBS += -fopenmp ( yes, it's also need in msvc)
LIBS += -lssp (It's required by mingw64)
BTW, if someone encounter a compile error when compiling opus by mingw, he could also need add -lssp in makefile.

**Comment by polusto** [comment]
Thank you for your input. The MSVC used to work, but there have been a lot of big changes recently and everything has not been kept up to date as it should have been. Sorry that you had go through unnecessary hoops. I'll comment MSVC out for now and remove those dll endings.
