### ISSUE TITLE
Question: How Kvazzup filter graph handles sending video

### ISSUE THREAD

**Issue by Thanh-Binh** [ultravideo/kvazzup#11]
I want to use my custom camera in Ubuntu.
I can add my custom camera in FilterGraph and see video in selfviewFilter_.
However, this video is not sent over Internet by calling. 
I know the camerafilter module is connected to SelfviewFilter, so that camera data can be displayed on it.
For debugging I nees an answer of following questions: 
1. what is video data flow from camera or screen sharing module to which module being response to send video out?
2. what modul is directly connected to camera module by Video Call?
Thanks

**Comment by polusto** [comment]
1. The sendVideoTo function in filter graph attaches the correct filters.
2. It depends on the camera format (YUV or RGB32). Either conversion filter or kvazaar directly if it is YUV. Kvazaar takes YUV

Answers to all video flow questions can be found by reading the code in Filter Graph class. I should be clear what it does. The addtograph function may add conversions if they are needed. Also our [paper](https://ieeexplore.ieee.org/abstract/document/8241673) explains the video flow.

**Comment by polusto** [comment]
I am relatively ok with small questions about how Kvazzup operates as long as they are not too much, but please don't ask me how you should implement something (unless it is going to result in a pull request), because I don't have time to get into the details of other peoples work.

**Comment by Thanh-Binh** [comment]
Understand thanks

**Comment by Thanh-Binh** [comment]
Interesting paper and excellent explanation!
It is clear now!
