### ISSUE TITLE
Qt is unable to get Camera parameters on Windows Surface Pro 7

### ISSUE THREAD

**Issue by DoS007** [ultravideo/kvazzup#12]
Hi, i was searching for a high quality video call program which support hevc and found this. Is this production ready to use or does this not really work? I'm using a windows surface pro 7 installed 0.09 and saw this in option (nothing selectable):

![grafik](https://user-images.githubusercontent.com/11618958/119889372-c2aa1e00-bf36-11eb-9c19-360a486bb010.png)

this isn't right, is it?

**Comment by polusto** [comment]
Hello and thank you for your interest in Kvazzup. 

Depends on what you mean by production ready. Kvazzup still has few key features (SIP NAT traversal, TLS, automatic encoding parameter adjustment) that are missing and I also haven't yet setup a system for creating SIP accounts to use with Kvazzup (although it is possible to setup your own SIP server). I try my best to fix all the bugs in Kvazzup, but there are still more testing needed to make this happen. I'm hoping to fix all bugs and get the basic features done this year and make Kvazzup into a high quality video call program supporting HEVC.

This particular bug seems to be Qt related and is probably somehow specific to Surface Pro and Qt. There is probably a need to submit a bug report to Qt. Linux Kvazzup has this same issue.

This is what it looks for me on Windows 10:
![image](https://user-images.githubusercontent.com/6498638/119942490-91fbd000-bf9a-11eb-8c4e-079a9ef68949.png)

Only existing software I know that supports HEVC (through hardware support) is Jami, but I haven't tested it and cannot say anything about its quality.

**Comment by polusto** [comment]
I don't know how Qt interacts on Surface Pro. It is also possible that Kvazzup needs to be specifically compiled for that platform to have the correct Qt libraries to get these parameters

**Comment by polusto** [comment]
I found these instruction: https://doc.qt.io/qt-5/winrt-support.html

If the build was built using those instructions, the camera might work better. 

All in all, I have to say Kvazzup releases probably don't support Windows Surface Pro at the moment. At some point later I might include the UWP builds with the release. Current build you are using is probably not compatible with UWP.

**Comment by DoS007** [comment]
Ok, thanks for your extensive response.

>Actually nothing in Kvazzup uses hardware acceleration for HEVC. The downside of this approach is the higher CPU usage, but the upside is better quality and lower bit rate compared to hardware acceleration. Kvazzup should be able to compete with (and hopefully beat) Skype in terms of quality and bit rate.

Hmm, ok. That might be a problem for me. Because HEVC is even more resource-intensive than h.264 and VP8; no hardware acceleration will be a probably a problem for resolutions >= FullHD? Especially for passive cpus. But I don't know how far it can go with fast coder preset.

__

It's interesting what you're telling. I would have thought it would be quite easy to make some peer to peer video call app, but that is probably very naive (like get an library for camera and one for media and codecs and one for internet transfer, even maybe all things by qt, stuck them together and voila, but that probably not so easy).

But what about browsers? Browsers give good api for camera, mic and also for hardware acceleration and one could use WebRTC?  (I think they use it e.g. on https://obs.ninja/ , probably also on talky but i think the last one is not open source).

Also found movim using jingle ( https://prosody.im/doc/jingle ). But never tested that. (jitsi, not jitsi meet, does not support fullhd).

**Comment by polusto** [comment]
> 
> 
> Ok, thanks for your extensive response.
> 

Take it with a grain of salt. I'm still learning these things and I would not be surprised if I didn't know something crucial.

> Hmm, ok. That might be a problem for me. Because HEVC is even more resource-intensive than h.264 and VP8; no hardware acceleration will be a probably a problem for resolutions >= FullHD? Especially for passive cpus. But I don't know how far it can go with fast coder preset.

You are right. At this point it will probably be difficult to run high resolutions on low-end CPU with Kvazzup. Kvazzup is capable of [4K calls](https://ieeexplore.ieee.org/abstract/document/8603283), but it needs decent CPU to do it. This should get better with time both in terms of how efficient Kvazzup and Kvazaar are and how fast CPUs are. As this is a research project, the focus is on the future. Of course hardware encoder is not unlimited source of quality calls either. Hardware has specific restriction that one cannot cross where as software performance is mostly only CPU bound. I'm not an expert on this, but hardware usually has a much higher bit rate.

I wouldn't be surprised if some day Kvazzup would also support hardware HEVC encoding, but at the moment it is not the most important task for me.

> __
> 
> It's interesting what you're telling. I would have thought it would be quite easy to make some peer to peer video call app, but that is probably very naive (like get an library for camera and one for media and codecs and one for internet transfer, even maybe all things by qt, stuck them together and voila, but that probably not so easy).

I don't think you are wrong. I was just speculating what could be the reasons for not having p2p calling. The problem for me has been that the existing libraries have not been very good and we have had to implement them ourselves. Especially lack of good modest size SIP implementation has taken a lot of my time.

> But what about browsers? Browsers give good api for camera, mic and also for hardware acceleration and one could use WebRTC? (I think they use it e.g. on https://obs.ninja/ , probably also on talky but i think the last one is not open source).

The reason why I didn't choose WebRTC was that browsers don't support HEVC. I can't say much more on that.

> Also found movim using jingle ( https://prosody.im/doc/jingle ). But never tested that. (jitsi, not jitsi meet, does not support fullhd).

Although XMPP(Jingle) can be used with SIP, there is much overlap and I probably don't need both at this point. Also prosody doesn't seem to support windows which is kind of a deal-breaker.

I must thank you for bringing me all this information. It is of course sad to hear that you are having problems finding software up to you standards, but for me this means there is a need for Kvazzup.

**Comment by jrsnen** [comment]
I've upgraded Kvazzup to Qt6 and added support for various input formats that were not supported before. I'm relatively confident that [v0.13.0](https://github.com/ultravideo/kvazzup/releases/tag/v0.13.0) fixes this issue. If there are still issues regarding video format settings, a new issue can be created.

Best Regards,
Joni Räsänen
