### ISSUE TITLE
Requesting guidance for ROI selection and encryption in HEVC coded video

### ISSUE THREAD

**Issue by Abhijeet241093** [ultravideo/kvazzup#2]
Hello Professor,

Thank you so much for your valuable contribution to the Field of Video encryption.

Could you please pity on me and guide me at this point "how you incorporated ROI in  HEVC code" ? 

How can select DC coefficient and motion vector from ROI and encrypt?  

Thank  you !!

**Comment by polusto** [comment]
Hello.

This is the repo for Kvazzup Video Call application which uses the Kvazaar HEVC encoder. I'm sorry, but I cannot help with matters concerning specifics of HEVC encoding. You might want to present your question to https://github.com/ultravideo/kvazaar

**Comment by Abhijeet241093** [comment]
Yes sir,

Thank you for yours response.





Sincerely,
Abhijeet Thakare,
Student,
Security Engineering lab,
Dept. of Computer and Information Security, Sejong University
209, Neungdong-ro, Gwangjin-gu, Seoul, South Korea, 143-747.
Ph:- +82 10-2155-0253
