### ISSUE TITLE
Screen sharing is not working

### ISSUE THREAD

**Issue by polusto** [ultravideo/kvazzup#5]
### Symptoms
Self view shows the shared screen correctly, but nothing is transmitted to call peers.

### Environment

All

### Reproduction
Call someone and enable screen sharing.

### Suspected Cause
The correct resolution is not set for Kvazaar filter and a bug fix removed the filters ability to adapt to different incoming resolutions.

**Comment by Thanh-Binh** [comment]
I found not only image resolution but frame rate must be set correctly.
I suggest a solution that must save those data of camera somewhere and they are read in Sharescreenfilter and resize the screen snapshot image to camera size!

**Comment by polusto** [comment]
This should now be fixed along with selection of shared screen in settings.
