### ISSUE TITLE
crashed after stop conference

### ISSUE THREAD

**Issue by Thanh-Binh** [ultravideo/kvazzup#8]
sometime for the case of call myself, after stopping the conference (by clicking on Stop-Button), it crashs.

**Comment by polusto** [comment]
This seems like a Linux only issue. Can you provide a stack trace from debugger by repeatedly calling and closing the call?

**Comment by Thanh-Binh** [comment]
Now I can identify the reason for it: when the audio sample rate is set more than 16000 so that the buffer will be full somehow.
I want to update the current version of uvgRTP, which supports now the data size until 65kB and show if the problem is solved?

**Comment by Thanh-Binh** [comment]
@polusto i have just updated the newest version and have a new problem that ini-file , section “video” after starting will be reset automatically.
I think it is a bug!
Could you pls check it? Thanks

**Comment by polusto** [comment]
668619006fa201193fb8e816d25beb02b44a3c37 should fix the settings restart issue.

**Comment by polusto** [comment]
I'm not sure if uvgRTP can handle audio larger than what is produced by sample rate of 16000. That is why it was set at that. This whole issue seems like a byproduct of not having working audio on Linux. I'm closing this as a duplicate of #7.
