### ISSUE TITLE
Compile problem with VS 2017

### ISSUE THREAD

**Issue by Thanh-Binh** [ultravideo/kvazzup#9]
it is too many problem by compiling with VS2017.
I have got error like
src\initiation\transaction\sipclient.cpp(93): error C2440: 'initializing': cannot convert from 'initializer list' to 'ViaInfo'
src\initiation\transaction\sipclient.cpp(93): note: No constructor could take the source type, or constructor overload resolution was ambiguous
sipdialog.cpp
src\initiation\transaction\sipdialog.cpp(30): error C2440: 'initializing': cannot convert from 'initializer list' to 'SIP_URI'
src\initiation\transaction\sipdialog.cpp(30): note: No constructor could take the source type, or constructor overload resolution was ambiguous
sipregistrations.cpp
src\initiation\transaction\sipregistrations.cpp(65): error C2440: 'initializing': cannot convert from 'initializer list' to 'SIP_URI'
src\initiation\transaction\sipregistrations.cpp(65): note: No constructor could take the source type, or constructor overload resolution was ambiguous
sipserver.cpp
src\initiation\transaction\sipserver.cpp(124): error C2440: 'initializing': cannot convert from 'initializer list' to 'SIP_URI'
src\initiation\transaction\sipserver.cpp(124): note: No constructor could take the source type, or constructor overload resolution was ambiguous

Do you have any idea?
Thanks

**Comment by polusto** [comment]
I cannot replicate this. 

Are you using Qt creator for compilation as suggested in readme?

Have you tried VS 2019?

**Comment by polusto** [comment]
I'm closing this since this seems to be a compiler version related problem. If there is more info on this issue it can be reopened.

**Comment by Thanh-Binh** [comment]
For VS, because many users want to use it but have many difficulties by compiling, I‘d like to say that we should support the users at least at the current version of VisualStudio 2019 as follows:
1. making available all dependent libs in a lib-folder
2. Make sure that pro-file works

**Comment by polusto** [comment]
@Thanh-Binh Can you create a new issue? It sound like you would like something to be done differently?
